### ISSUE TITLE
Question regarding the implementation of CLValue and deserialization

### ISSUE THREAD

**Issue by aryaxt** [casper-network/casper-java-sdk#102]
If I understand correctly in order to read a stored value of a contract, a call to `state_get_item` is made which returns a CLValue,

When deserializing CLValue, to extract the actual value (Int, String, Map) the field `parsed` is read, rather than reversing the custom serialization from `cl_bytes`. But then why is there a [comment](https://github.com/casper-network/casper-java-sdk/blob/main/src/main/java/com/casper/sdk/types/CLValue.java#L19) on CLValue.parsed that says:

"The optional parsed value of the bytes used when testing"
Why does it say "optional"? and why does it say "when testing"?

**Comment by meywood** [comment]
When constructing values the parsed value is there to provide human readable version in the JSON rather than having just the raw bytes. 

Both of the following are valid as far as the node is concenred:
```
// Value containing optional parsed
 {
            "cl_type" : "U512",
            "bytes" : "0500e40b5402",
            "parsed" : 10000000000
 }

// Value without optional parsed, also valid
 {
            "cl_type" : "U512",
            "bytes" : "0500e40b5402"
 }
```
