### ISSUE TITLE
Contracts: StoredContractByNameVersioned

### ISSUE THREAD

**Issue by momipsl** [casper-network/casper-java-sdk#45]
To execute a smart contract's entry point one can invoke a versioned contract by name. This is one of 6 ExecutableDeployItem variants.

**Comment by i-mills** [comment]
Just has a look @ the docs for StoredVersionedContractByName in https://docs.casperlabs.io/en/latest/implementation/serialization-standard.html and am seeing non-standard JSON:

`StoredVersionedContractByName { name: "lWJWKdZUEudSakJzw1tn", version: Some(1632552656), entry_point: "S1cXRT3E1jyFlWBAIVQ8", args: 9975e6957ea6b07176c7d8471478fb28df9f02a61689ef58234b1a3cffaebf9f303e3ef60ae0d8 }`

is version really: version: Some(1632552656)? or is it version: "Some(1632552656)" if it is the former the Java JSON parser will not be able to read the JSON and we'll have to preprocess it. Can you add some real JSON examples to the ticket please.
