### ISSUE TITLE
getRPCSchema

### ISSUE THREAD

**Issue by i-mills** [casper-network/casper-java-sdk#83]

**Comment by i-mills** [comment]
Hi @cryptofervid thanks for the heads up :) . I've refactored the NodeClient so will resolved conflicts and merge in your branch tomorrow. I think Casper lab’s arse isn't talking to its elbow, as Carl and I were asked to implement these methods last week

**Comment by cryptofervid** [comment]
@i-mills That would be great. Please also look at the other PRs I have put in. #77 implements method to fetch node metrics from the Casper node. 

Since you were asked to implement all these methods recently I assume judges have not looked at my PRs and my hackathon effort might go waste :(
