### ISSUE TITLE
Crypto: get-keypair-from-seed (ED25519)

### ISSUE THREAD

**Issue by momipsl** [casper-network/casper-java-sdk#86]
Deterministic key pair generation is predicated upon using so-called **seeds**, i.e. 32 bytes of entropy / randomness.  Such seeds are often stored within hardware wallets.  Therefore the key pair factory needs an overloaded function that accepts the seed.

**Comment by momipsl** [comment]
Reviewing the [python SDK implementation](https://github.com/casper-network/casper-python-sdk/blob/main/pycspr/crypto/ecc_ed25519.py#L13-L25) may be of use.

**Comment by yanwankun** [comment]
In fact, the number of people using java may be more, so it is also very good to implement it in java

**Comment by Murasame233** [comment]
When this feature will be release? It almost 1 month later. I need this function for dev. Any help can I do?
