### ISSUE TITLE
Events: Event channels extended

### ISSUE THREAD

**Issue by asladeofgreen** [casper-network/casper-java-sdk#88]
1. Each of the 3 event channels (main, deploys, sigs) will be augmented with a new event called Shutdown.  It is emitted in the event of the node shutting down.  The event data is a simple string rather than a JSON data structure.  For example:
```
data:"Shutdown"
id:352

```

2. The main event channel is being augmented with a new event type: DeployExpired.  This event is emitted when a buffered deploy ttl expires.

**Comment by momipsl** [comment]
The relevant PR in casper-node: https://github.com/casper-network/casper-node/pull/2177/files
